#!/bin/bash
#This script is executed every time your instance is spawned.

# copy files to home folder
cp -af ~/my_data/home/. ~/

# add Powerline font for tmux
font_dir="$HOME/.local/share/fonts"
mkdir -p $font_dir
cp "$HOME/my_data/fonts/Cousine for Powerline.ttf" ~/.local/share/fonts/

# refresh font cache
if which fc-cache >/dev/null 2>&1 ; then
    fc-cache -f "$font_dir"
fi

# load mate-terminal profiles
source ~/my_data/import-mate-terminal.sh

# add aliases
    # commands

alias cd..='cd ..'
alias ..='cd ..'
alias ll='ls -oAFHcthr'
alias h='history'
alias wget='wget -c'

    # handy new commands

alias ports='netstat -tulanp'
alias ip ='/sbin/ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1'

    # safety nets

alias rm='rm -I --preserve-root'
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

